services:
  backend:
    build: ./backend
    container_name: langchain-backend
    env_file:
      - .env   
    environment:
      - VLLM_API_BASE=${VLLM_API_BASE}
      - MS_CLIENT_ID=${MS_CLIENT_ID}
      - MS_CLIENT_SECRET=${MS_CLIENT_SECRET}
      - MS_TENANT_ID=${MS_TENANT_ID}
      - MS_SCOPE=${MS_SCOPE}

    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/checkpoints:/app/checkpoints
  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
      - "8443:443"  
    depends_on:
      - backend
    volumes:
      - ./frontend/ssl:/etc/nginx/ssl

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8081:8080"
    volumes:
      - ./searxng/settings/settings.yml:/etc/searxng/settings.yml
    environment:
      - SEARXNG_SECRET=502081bb13533d7d11666f55dccaba5f2051936adff9918473be33fa18302136

