services:
  backend:
    build: ./backend
    container_name: langchain-backend
    env_file:
      - .env   
    environment:
      - VLLM_API_BASE=${VLLM_API_BASE}
      - MS_CLIENT_ID=${MS_CLIENT_ID}
      - MS_CLIENT_SECRET=${MS_CLIENT_SECRET}
      - MS_TENANT_ID=${MS_TENANT_ID}
      - MS_SCOPE=${MS_SCOPE}

    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/checkpoints:/app/checkpoints
  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend



