def generate_email_reply(query: str) -> str:
    """
    Generate an email reply based on the chat state.
    
    Args:
    state (AgentState): The current state of the chat session.
    
    Returns:
    AgentState: The updated chat state with the email reply.
    """
    print(f"in generate: {query}")
    reply = f"""
    Dear Client,

    Thank you for your inquiry. Based on your request:
    {query}

    If you have any further questions, feel free to reach out.

    This email was automatically generated by BDM.chat assistant.
    """
    
    return reply