def generate_email_reply(query: str) -> str:
    reply = f"""
    Dear Client,

    Thank you for your inquiry. Based on your request:
    {query}

    If you have any further questions, feel free to reach out.

    This email was automatically generated by BDM.chat assistant.
    """
    
    return reply